const gradientsByType = (type) => ({
    grass: {   backgroundColor: "white" },
    fire: { backgroundColor: "white" },
    water: { backgroundColor: "white" },
    electric: { backgroundColor: "white" },
    normal: { backgroundColor: "white" },
    poison: { backgroundColor: "white" },
    ground: { backgroundColor: "white" },
    fairy: { backgroundColor: "white" },
    fighting: { backgroundColor: "white" },
    flying: { backgroundColor: "white" },
    dragon: { backgroundColor: "white" },
    ice: { backgroundColor: "white" },
    ghost: { backgroundColor: "white" },
    steel: { backgroundColor: "white" },
    rock: { backgroundColor: "white" },
    dark: { backgroundColor: "white" },
    unknown: { backgroundColor: "white" },
    shadow: { backgroundColor: "white" },
    bug: { backgroundColor: "white" },
    psychic: { backgroundColor: "white" },
    intimidate: { backgroundColor: "white" },
  });
